version: "3.8"
name: "netrunner_compose"


services:
  database:
    image: postgres:14
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    networks:
      - backend-network
    restart: always

  auth:
    image: quay.io/keycloak/keycloak:22.0.1
    ports:
      - "8180:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
      - --import-realm
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=dir"
      - "-Dkeycloak.migration.dir=/opt/keycloak/data/import"
      - "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING"
    volumes:
      - ./realms:/opt/keycloak/data/import
    networks:
      - backend-network

    restart: always

  backend:
    image: ge0rg25/netrunner-backend:latest
    ports:
      - "2000:2000"
    depends_on:
      - auth
      - database
    environment:
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      KEYCLOAK_SECRET: "**********"
      KEYCLOAK_HOST: auth
      KEYCLOAK_PORT: 8080
    networks:
      - backend-network
    restart: always


networks:
  backend-network: