version: "1.0"
name: "netrunner_compose"

services:
  database:
    image: postgres:14
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 5432:5432
    networks:
      - backend-network

  auth:
    image: ge0rg25/netrunner-auth:latest
    ports:
      - 8180:8180
    networks:
      - backend-network


networks:
  backend-network: