version: "3.8"
name: "netrunner_compose"


services:
  database:
    image: postgres:14
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    networks:
      - backend-network
    restart: always

  auth:
    image: quay.io/keycloak/keycloak:22.0.1
    ports:
      - "3000:8080"
      - "3443:8443"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/tls.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/tls.key
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./netrunner-realm.json:/opt/keycloak/data/import/netrunner-realm.json
      - ./certs/fullchain.pem:/etc/x509/https/tls.crt
      - ./certs/privkey.pem:/etc/x509/https/tls.key
    networks:
      - backend-network

    restart: always

  backend:
    image: ge0rg25/netrunner-backend:latest
    ports:
      - "2000:2000"
    depends_on:
      - auth
      - database
    environment:
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      KEYCLOAK_HOST: auth
      KEYCLOAK_PORT: 8080
    networks:
      - backend-network
    restart: always

  frontend:
    image: ge0rg25/netrunner-frontend:latest
    ports:
      - "80:8080"
    depends_on:
      - backend
    restart: always


networks:
  backend-network: