version: "3.8"
name: "netrunner_compose"


services:
  database:
    image: postgres:14
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    networks:
      - backend-network
    restart: always


  backend:
    image: ge0rg25/netrunner-backend:latest
    ports:
      - "2000:2000"
    depends_on:
      - database
    environment:
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      KEYCLOAK_SECRET: wKe06lR76VWQUnQXnVjCI4TCgo88nWHU
      KEYCLOAK_HOST: localhost
      KEYCLOAK_PORT: 8080
    networks:
      - backend-network
    restart: always


networks:
  backend-network: