version: "3.8"
name: "netrunner_compose"

services:
  database:
    image: postgres:14
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    networks:
      - backend-network


  auth:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8180:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./realm.json:/opt/keycloak/data/import/realm.json
    networks:
      - backend-network
    platform: "linux/amd64"

  backend:
    image: ge0rg25/netrunner-backend:latest
    ports:
      - "2000:2000"
    depends_on:
      - auth
      - database
    environment:
      POSTGRES_HOST: database
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      KEYCLOAK_HOST: auth
    networks:
      - backend-network


networks:
  backend-network: