# production environment
FROM nginx:latest as production-stage
WORKDIR /app
COPY /frontend /usr/share/nginx/html
# new
COPY /nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]